<?php
// Automatically created cache file for the package format
// Do not modify this file

$CacheCodeDate = 1069339607;

$Parameters = array( "name" => "ezdemo_democontent",
                     "development" => false,
                     "summary" => "",
                     "description" => "",
                     "vendor" => "eZ systems",
                     "vendor-dir" => "eZ-systems",
                     "priority" => false,
                     "type" => "contentobject",
                     "extension" => false,
                     "install_type" => "install",
                     "ezpublish" => array( "version" => "5.4.0-beta1",
                                           "named-version" => "5.4" ),
                     "maintainers" => array( array( "name" => "Administrator User",
                                                    "email" => "nospam@ez.no",
                                                    "role" => "lead" ) ),
                     "packaging" => array( "timestamp" => "1300109477",
                                           "host" => "packages.ez.no",
                                           "packager" => false ),
                     "source" => false,
                     "documents" => array( array( "name" => "LICENCE",
                                                  "mime-type" => "text/plain",
                                                  "os" => "",
                                                  "data" => false,
                                                  "audience" => "" ) ),
                     "groups" => array(),
                     "changelog" => array( array( "timestamp" => "1300109477",
                                                  "person" => "Administrator User",
                                                  "email" => "bk@ez.no",
                                                  "changes" => array( "Creation of package." ),
                                                  "release" => "1" ) ),
                     "file-list" => array(),
                     "simple-file-list" => array( "dcbbca71f9115439cb1a47e9093c4d86" => array( "original-path" => "var/ezdemo_site/storage/images/getting-started/selected-features/automate/1283-5-eng-GB/Automate.jpg",
                                                                                               "package-path" => "simplefiles/ba2a2bea.jpg" ),
                                                  "324db4a22b0841c40e10a153e13f9f77" => array( "original-path" => "var/ezdemo_site/storage/images/getting-started/selected-features/deliver/265-2-eng-GB/Deliver.jpg",
                                                                                               "package-path" => "simplefiles/c97d7955.jpg" ),
                                                  "4daa5223cf84e604df452bbcf77edd44" => array( "original-path" => "var/ezdemo_site/storage/images/getting-started/selected-features/create/277-3-eng-GB/Create.jpg",
                                                                                               "package-path" => "simplefiles/92f022f1.jpg" ),
                                                  "b30c789136efae94eb10e575b887a799" => array( "original-path" => "var/ezdemo_site/storage/images/getting-started/selected-features/optimize/289-3-eng-GB/Optimize.jpg",
                                                                                               "package-path" => "simplefiles/bb64019b.jpg" ),
                                                  "5b71995be15fb77afea60fb3c5305353" => array( "original-path" => "var/ezdemo_site/storage/images/getting-started/selected-features/getting-started-with-ez-publish-5/301-4-eng-GB/Getting-Started-with-eZ-Publish-5.jpg",
                                                                                               "package-path" => "simplefiles/1f96ad5f.jpg" ),
                                                  "58564f4b7283a1af95eebb6c37c6f3a6" => array( "original-path" => "var/ezdemo_site/storage/images/shopping/products/ez-publish-community-iphone-4-case/1367-1-eng-GB/eZ-Publish-Community-iPhone-4-Case.jpg",
                                                                                               "package-path" => "simplefiles/94bbf784.jpg" ),
                                                  "6e4400f4c3a9829c371051c2904d6de2" => array( "original-path" => "var/ezdemo_site/storage/images/shopping/products/ez-publish-samsung-galaxy-siii-case/1378-1-eng-GB/eZ-Publish-Samsung-Galaxy-SIII-Case.jpg",
                                                                                               "package-path" => "simplefiles/d1452126.jpg" ),
                                                  "a728d6d6c96638e0f092698aa68aab92" => array( "original-path" => "var/ezdemo_site/storage/images/shopping/products/ez-publish-community-mug/1389-1-eng-GB/eZ-Publish-Community-Mug.png",
                                                                                               "package-path" => "simplefiles/94ba49af.png" ),
                                                  "33a16d8fd3c6a729a2422a220a4a0b41" => array( "original-path" => "var/ezdemo_site/storage/images/shopping/products/ez-publish-man-jacket/1400-1-eng-GB/eZ-Publish-Man-jacket.jpg",
                                                                                               "package-path" => "simplefiles/9f7c6a08.jpg" ),
                                                  "4aba060e50a2641bdba5539a97a167b0" => array( "original-path" => "var/ezdemo_site/storage/images/shopping/services/support-maintenance/2486-5-eng-GB/Support-Maintenance.jpg",
                                                                                               "package-path" => "simplefiles/4ff73fcb.jpg" ),
                                                  "9a373cdd0838deaf5a855dcc649a82cd" => array( "original-path" => "var/ezdemo_site/storage/images/shopping/services/professional-services/2498-2-eng-GB/Professional-Services.jpg",
                                                                                               "package-path" => "simplefiles/d08e25a3.jpg" ),
                                                  "366fa3244fb4cd170e07218d9920eb9d" => array( "original-path" => "var/ezdemo_site/storage/images/shopping/services/training-services/2510-3-eng-GB/Training-Services.jpg",
                                                                                               "package-path" => "simplefiles/138f5201.jpg" ),
                                                  "d5a4e04e9207c6e82213ffb7be01a1d5" => array( "original-path" => "var/ezdemo_site/storage/images/shopping/services/ez-publish-enterprise-service/451-6-eng-GB/eZ-Publish-Enterprise-Service.jpg",
                                                                                               "package-path" => "simplefiles/f6ff91ab.jpg" ),
                                                  "cfb134a6699adeef34bb96c56265b3c6" => array( "original-path" => "var/ezdemo_site/storage/images/shopping/services/ez-publish-enterprise-service/squares/548-1-eng-GB/squares.png",
                                                                                               "package-path" => "simplefiles/a825a4dc.png" ),
                                                  "c92effff1d66b1073d92b0932b0f133c" => array( "original-path" => "var/ezdemo_site/storage/original/image/e76c8776dccaba21cbfc21f52a02e19f.png",
                                                                                               "package-path" => "simplefiles/0e753680.png" ),
                                                  "282c5b7862371e3651a20204422cc4ac" => array( "original-path" => "var/ezdemo_site/storage/original/image/5abdfbefae47de9dca63bc43e3a23ff4.png",
                                                                                               "package-path" => "simplefiles/0508ba70.png" ),
                                                  "fadf75fc8fa655212e59f7a3f92af634" => array( "original-path" => "var/ezdemo_site/storage/images/10-tips-to-quickly-discover-stetind-and-ez-publish-5/landing1/1248-1-eng-GB/landing1.jpg",
                                                                                               "package-path" => "simplefiles/c76e90df.jpg" ),
                                                  "05171a31d40a40d9d3d084befbfb8fdd" => array( "original-path" => "var/ezdemo_site/storage/original/application/63cd472dd7819da7b75e8e2fee507c68.pdf",
                                                                                               "package-path" => "simplefiles/530ddbca.pdf" ),
                                                  "1127499c0508f13c7149661768389db2" => array( "original-path" => "var/ezdemo_site/storage/images/media/images/screen-shot-2013-01-31-at-8.17.26-pm/1297-1-eng-GB/Screen-Shot-2013-01-31-at-8.17.26-PM.png",
                                                                                               "package-path" => "simplefiles/07cad76d.png" ),
                                                  "6479c23df792b75664100b579c86c03e" => array( "original-path" => "var/ezdemo_site/storage/images/media/images/funel2/1413-1-eng-GB/funel.png",
                                                                                               "package-path" => "simplefiles/1e653715.png" ),
                                                  "e287e065f2289fab8979f479a017426f" => array( "original-path" => "var/ezdemo_site/storage/images/about/the-mountains-of-ez/mount-matterhorn/1523-1-eng-GB/mount-matterhorn.jpg",
                                                                                               "package-path" => "simplefiles/3963f0b6.jpg" ),
                                                  "c519455777f8e3d70eb9e305f41139ec" => array( "original-path" => "var/ezdemo_site/storage/images/about/the-mountains-of-ez/mount-annapurna/1528-1-eng-GB/mount-annapurna.jpg",
                                                                                               "package-path" => "simplefiles/38d686e0.jpg" ),
                                                  "e0275413e3a896b6587c3fcab1ad932e" => array( "original-path" => "var/ezdemo_site/storage/images/about/the-mountains-of-ez/mount-stetind/1533-1-eng-GB/mount-stetind.jpg",
                                                                                               "package-path" => "simplefiles/05d34e35.jpg" ),
                                                  "e4222d7656e76e5c6a398128df826d3e" => array( "original-path" => "var/ezdemo_site/storage/images/about/the-mountains-of-ez/mount-ventoux/1538-1-eng-GB/mount-ventoux.jpg",
                                                                                               "package-path" => "simplefiles/2323304e.jpg" ),
                                                  "2e41bd01e9c8d23aba9d31a52413fd54" => array( "original-path" => "var/ezdemo_site/storage/images/about/the-mountains-of-ez/mount-kilimanjaro/1543-1-eng-GB/mount-kilimanjaro.jpg",
                                                                                               "package-path" => "simplefiles/b970cf62.jpg" ),
                                                  "21ab248afb36298bc2356b83069fb1ea" => array( "original-path" => "var/ezdemo_site/storage/images/about/the-mountains-of-ez/mount-etna/1548-1-eng-GB/mount-etna.jpg",
                                                                                               "package-path" => "simplefiles/e08a9864.jpg" ),
                                                  "7256dbd01f723a86d0f4f081656d7ca2" => array( "original-path" => "var/ezdemo_site/storage/images/about/the-mountains-of-ez/mount-fuji/1558-1-eng-GB/mount-fuji.jpg",
                                                                                               "package-path" => "simplefiles/58504932.jpg" ),
                                                  "f978c52678bc8ca8b1043c838d005adf" => array( "original-path" => "var/ezdemo_site/storage/images/about/the-mountains-of-ez/mount-aconcagua/1563-1-eng-GB/mount-aconcagua.jpg",
                                                                                               "package-path" => "simplefiles/8d6f1f98.jpg" ),
                                                  "0121cb57124840749b68a8da7de79716" => array( "original-path" => "var/ezdemo_site/storage/original/video/cbca3a8812784f3989158d295cc0c016.mp4",
                                                                                               "package-path" => "simplefiles/ed958bed.mp4" ),
                                                  "acb69750298ff73d6e5726c04c60e22b" => array( "original-path" => "var/ezdemo_site/storage/images/ez-mountains/mount-fuji/632-2-eng-GB/Mount-Fuji.jpg",
                                                                                               "package-path" => "simplefiles/d5c11bd1.jpg" ),
                                                  "0e54bdfbe8c4d5b4a539a87afeca0dbb" => array( "original-path" => "var/ezdemo_site/storage/images/ez-mountains/mount-matterhorn/638-2-eng-GB/Mount-Matterhorn.jpg",
                                                                                               "package-path" => "simplefiles/7df85099.jpg" ),
                                                  "114b45da7bd17da85121e6f06ef64f74" => array( "original-path" => "var/ezdemo_site/storage/images/ez-mountains/mount-annapurna/644-2-eng-GB/Mount-Annapurna.jpg",
                                                                                               "package-path" => "simplefiles/553bfea2.jpg" ),
                                                  "3ad8ff8e32b9b1040e70239fc3f2b633" => array( "original-path" => "var/ezdemo_site/storage/images/ez-mountains/mount-etna/650-3-eng-GB/Mount-Etna.jpg",
                                                                                               "package-path" => "simplefiles/f5aab896.jpg" ),
                                                  "3cd9223e45e7414f0422ac7632afcdb2" => array( "original-path" => "var/ezdemo_site/storage/images/ez-mountains/mount-kilimanjaro/656-2-eng-GB/Mount-Kilimanjaro.jpg",
                                                                                               "package-path" => "simplefiles/944650b0.jpg" ),
                                                  "968c543d732a626d01e3e393971bb531" => array( "original-path" => "var/ezdemo_site/storage/images/ez-mountains/mount-stadda/662-2-eng-GB/Mount-Stadda.jpg",
                                                                                               "package-path" => "simplefiles/4418140f.jpg" ),
                                                  "c1d90a5b7f607a660972bdc8b01b555a" => array( "original-path" => "var/ezdemo_site/storage/images/ez-mountains/mount-aconcagua/668-2-eng-GB/Mount-Aconcagua.jpg",
                                                                                               "package-path" => "simplefiles/08cbe9b8.jpg" ),
                                                  "f1758fd41ac3aff654b6db0fabb66086" => array( "original-path" => "var/ezdemo_site/storage/images/ez-mountains/mount-ventoux/674-2-eng-GB/Mount-Ventoux.jpg",
                                                                                               "package-path" => "simplefiles/f2744337.jpg" ) ),
                     "version-number" => "5.4",
                     "release-number" => "0-beta1",
                     "release-timestamp" => false,
                     "licence" => "GPL",
                     "state" => "stable",
                     "dependencies" => array( "provides" => array(),
                                              "requires" => array(),
                                              "obsoletes" => array(),
                                              "conflicts" => array() ),
                     "install" => array( array( "type" => "ezcontentobject",
                                                "name" => "",
                                                "os" => "",
                                                "filename" => "contentobjects",
                                                "sub-directory" => "ezcontentobject" ) ),
                     "uninstall" => array( array( "type" => "ezcontentobject",
                                                  "name" => "",
                                                  "os" => "",
                                                  "filename" => "contentobjects",
                                                  "sub-directory" => "ezcontentobject" ) ) );
$InstallData = array();
$RepositoryPath = "var/storage/packages/eZ-systems";
?>
